server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice_microservice
    username: postgres
    password: Dhruvgoel@261062
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true